import fs from "node:fs/promises";
import path, { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { XMLParser } from "fast-xml-parser";
import { z } from "zod/v4";

import { documentationBaseUrl } from "./index";
import { integrationDocSlugs } from "./integration-doc-slugs";
import { widgetDocSlugs } from "./widget-doc-slugs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// The docs site is published under a baseUrl ("/muninn"), so every sitemap loc
// carries that prefix. Paths in the generated union are baseUrl-free, because
// createDocumentationLink concatenates them onto documentationBaseUrl, which
// already includes it.
const basePathPrefix = new URL(documentationBaseUrl).pathname.replace(/\/$/, "");

const toSitePath = (loc: string) => {
  const { pathname } = new URL(loc);
  const withoutBase =
    basePathPrefix && pathname.startsWith(basePathPrefix) ? pathname.slice(basePathPrefix.length) : pathname;
  return withoutBase.replace(/\/$/, "");
};

const sitemapSchema = z.object({
  urlset: z.object({
    url: z.array(
      z.object({
        loc: z.string(),
      }),
    ),
  }),
});

// apps/docs/build is gitignored, so the sitemap only exists after a local
// Docusaurus build. This codegen is therefore run by hand and its output is a
// committed artifact - see the codegen:docs script.
const sitemapPath = path.join(__dirname, "../../../../apps/docs/build/sitemap.xml");

const readSitemapAsync = async () => {
  return await fs.readFile(sitemapPath, "utf8");
};

const parseXml = (sitemapXml: string) => {
  const parser = new XMLParser();
  const data: unknown = parser.parse(sitemapXml);
  const result = sitemapSchema.safeParse(data);
  if (!result.success) {
    throw new Error("Invalid sitemap schema");
  }

  return result.data;
};

const mapSitemapXmlToPaths = (sitemapData: z.infer<typeof sitemapSchema>) => {
  return sitemapData.urlset.url.map((url) => toSitePath(url.loc)).filter((sitePath) => sitePath.length > 0);
};

const createSitemapPathType = (paths: string[]) => {
  return "export type MuninnDocumentationPath =\n" + paths.map((path) => `  | "${path}"`).join("\n");
};

const updateSitemapTypeFileAsync = async (sitemapPathType: string) => {
  const content =
    "// This file is auto-generated by the codegen script\n" +
    "// it uses the sitemap.xml to generate the MuninnDocumentationPath type\n" +
    sitemapPathType +
    ";\n";

  await fs.writeFile(outputPath, content);
};

const slugMapPaths = [
  ...Object.values(integrationDocSlugs)
    .filter(Boolean)
    .map((slug) => `/docs/integrations/${slug}`),
  ...Object.values(widgetDocSlugs)
    .filter(Boolean)
    .map((slug) => `/docs/widgets/${slug}`),
];

const outputPath = path.join(__dirname, "muninn-docs-sitemap.ts");

const main = async () => {
  let sitemapXml: string;
  try {
    sitemapXml = await readSitemapAsync();
  } catch {
    // No build on disk. Leave the committed artifact alone rather than
    // regenerating it from the slug maps and silently losing every other route.
    console.warn(`No sitemap at ${sitemapPath}. Run \`pnpm -F @homarr/docs build\` first; keeping the existing file.`);
    return;
  }

  const paths = mapSitemapXmlToPaths(parseXml(sitemapXml));
  paths.push("/sitemap.xml");
  for (const p of slugMapPaths) {
    if (!paths.includes(p)) {
      paths.push(p);
    }
  }

  const sitemapPathType = createSitemapPathType([...new Set(paths)]);
  await updateSitemapTypeFileAsync(sitemapPathType);
};

void main();
