CREATE TABLE `oidcProvider` (
	`id` varchar(64) NOT NULL,
	`key` varchar(64) NOT NULL,
	`display_name` text NOT NULL,
	`provider_type` varchar(64) NOT NULL,
	`enabled` boolean NOT NULL DEFAULT true,
	`show_on_login` boolean NOT NULL DEFAULT true,
	`is_default` boolean NOT NULL DEFAULT false,
	`client_id` text NOT NULL,
	`client_secret` text NOT NULL,
	`issuer` text,
	`discovery_url` text,
	`tenant` varchar(128),
	`authorization_url` text,
	`token_url` text,
	`userinfo_url` text,
	`scopes` text,
	`token_endpoint_auth_method` varchar(64) NOT NULL DEFAULT 'client_secret_basic',
	`allow_dangerous_email_account_linking` boolean NOT NULL DEFAULT false,
	`force_userinfo` boolean NOT NULL DEFAULT false,
	`name_claim` varchar(128),
	`email_claim` varchar(128),
	`picture_claim` varchar(128),
	`username_claim` varchar(128),
	`groups_claim` varchar(128),
	`allowed_groups` text,
	`admin_groups` text,
	`groups_local_management` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL,
	`updated_at` timestamp NOT NULL,
	CONSTRAINT `oidcProvider_id` PRIMARY KEY(`id`),
	CONSTRAINT `oidcProvider_key_unique` UNIQUE(`key`)
);
